services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/target
    environment:
      - VIRTUAL_ENV=/venv
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: sh -c "maturin develop --release && bash"
