import os
from pathlib import Path

def process_file(path: str) -> str: ...
def process_files(*paths: str | os.PathLike) -> list[str]: ...
def _cache_shutdown() -> None: ...

class Client:
    def __init__(self, paths: list[str] | list[os.PathLike]) -> None: ...
    def test(self) -> None: ...
    def search(self, query: str) -> list[tuple[Path, list[str]]]: ...
    def sem_search(self, query: str) -> list[tuple[Path, list[str]]]: ...
