import os
from pathlib import Path

def process_file(path: str) -> str: ...
def process_files(*paths: str | os.PathLike) -> list[str]: ...
def _cache_shutdown() -> None: ...

class Client:
    def __init__(self, paths: list[str] | list[os.PathLike]) -> None: ...
    def search(self, query: Query) -> list[tuple[Path, list[SearchResult]]]: ...
    def sem_search(self, query: Query) -> list[tuple[Path, list[SearchResult]]]: ...

class Query:
    def __init__(self, term: str, before: int = 0, after: int = 0): ...

class SearchResult:
    def before(self) -> str: ...
    def matched(self) -> str: ...
    def after(self) -> str: ...
