import os
from pathlib import Path

from scan_search.config import ScanSearchConfig

def _cache_shutdown() -> None: ...
def get_tessdata_dir() -> str: ...

class Client:
    def __init__(self, config: ScanSearchConfig, paths: list[str] | list[os.PathLike]) -> None: ...
    def search(self, query: Query) -> list[tuple[Path, list[SearchResult]]]: ...
    def sem_search(self, query: Query) -> list[tuple[Path, list[SearchResult]]]: ...

class Query:
    def __init__(self, term: str, before: int = 0, after: int = 0): ...

class SearchResult:
    def before(self) -> str: ...
    def matched(self) -> str: ...
    def after(self) -> str: ...
